[workspace]
members = [ "common", "node_lib", "rsu_lib", "obu_lib", "simulator", "node", "visualization", "scripts_tools" ]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
