[package]
name = "server_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
common = { path = "../common" }
mac_address = "*"
node_lib = { path = "../node_lib" }
tokio = { version = "1.0", features = ["net", "rt-multi-thread", "macros", "sync"] }
tokio-tun = "*"
tracing = "0.1"

[features]
test_helpers = ["node_lib/test_helpers"]